REM CREAR OTRO USUARIO PARA EL EXAMEN 3 CON ESQUEMA distribuitor
CREATE USER EX3 IDENTIFIED BY X3
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, RESOURCE TO EX3;
CONNECT EX3/X3;
REM CARGAR EL SCHEMA DISTRIBUITOR
@C:\Users\USER20\Documents\7mo\DBDistributed\examenes\examen3\scripts_Mastering_PLSQL.sql
REM VER LAS TABLAS CREADAS POR EL USUARIO EX3
select owner, table_name from all_tables
where owner like '%EX3%';

